import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import FixedBarTemplate from "@/components/templates/fixed-bar/FixedBarTemplate";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <FixedBarTemplate/>
        <div id="main" className="px-[2%] max-w-[1700px] mx-auto">
          {children}
        </div>
      </body>
    </html>
  );
}