import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AppBar from "@/components/organisms/appbar/AppBar";
import CategorySideBar from "@/components/organisms/sidebar/category/CategorySideBar";
import BasketSideBar from "@/components/organisms/sidebar/basket/BasketSideBar";
import AccountSideBar from "@/components/organisms/sidebar/account/AccountSideBar";
import NavBar from "@/components/organisms/navbar/NavBar";
import BarTemplate from "@/components/templates/bar/BarTemplate";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <BarTemplate/>
        <div id="main" className="px-[2%] max-w-[1700px] mx-auto">
          {children}
        </div>
      </body>
    </html>
  );
}